/*
@Autor:           Belmont Muñoz Samuel
                  Capistrán Manuel
@Fecha creación:  dd/mm/yyyy
@Descripción:     Archivo principal
*/

Prompt concetando a PDB &p_pdb

connect sys/&p_sys_pwd@&p_pdb as sysdba

--crear roles
DROP ROLE IF EXISTS ROL_ADMIN;

CREATE ROLE ROL_ADMIN;

DROP ROLE IF EXISTS ROL_INVITADO;

CREATE ROLE ROL_INVITADO;

-- Asignar privilegios a los roles

GRANT CREATE TABLE, CREATE SESSION, CREATE SEQUENCE, CREATE PROCEDURE,
CREATE TRIGGER, CREATE SYNONYM, CREATE PUBLIC SYNONYM, CREATE VIEW TO ROL_ADMIN;

GRANT CREATE SESSION, CREATE SYNONYM TO ROL_INVITADO;

DROP USER IF EXISTS &P_USUARIO_ADMIN CASCADE;

CREATE USER &P_USUARIO_ADMIN IDENTIFIED BY &p_password QUOTA UNLIMITED ON USERS;

DROP USER IF EXISTS &P_USUARIO_INVITADO CASCADE;

CREATE USER &P_USUARIO_INVITADO IDENTIFIED BY &p_password QUOTA UNLIMITED ON USERS;

-- Asignar los roles a los usuarios
GRANT ROL_ADMIN TO &P_USUARIO_ADMIN;

GRANT ROL_INVITADO TO &P_USUARIO_INVITADO;

DISCONNECT
