
-- Secuencia para la tabla ENTIDAD
CREATE SEQUENCE ENTIDAD_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 33
    NOCYCLE;

-- Secuencia para la tabla PLACA
CREATE SEQUENCE PLACA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

-- Secuencia para la tabla PROPIETARIO
CREATE SEQUENCE PROPIETARIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para la tabla LICENCIA
CREATE SEQUENCE LICENCIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

-- Secuencia para la tabla MARCA
CREATE SEQUENCE MARCA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

-- Secuencia para la tabla MODELO
CREATE SEQUENCE MODELO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

-- Secuencia para la tabla VEHICULO
CREATE SEQUENCE VEHICULO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;


-- Secuencia para la tabla HISTORICO_ESTATUS_VEHICULO
CREATE SEQUENCE HISTORICO_ESTATUS_VEHICULO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

-- Secuencia para la tabla VERIFICACION
CREATE SEQUENCE VERIFICACION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;


-- Secuencia para la tabla REPORTE_EMISIONES
CREATE SEQUENCE REPORTE_EMISIONES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;
    
-- Secuencia para la tabla NOTIFICACION

CREATE SEQUENCE NOTIFICACION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

-- Secuencia para la tabla HISTORICO_PROPIETARIO_VEHICULO
CREATE SEQUENCE HISTORICO_PROPIETARIO_VEHICULO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;