-- Índices Non Unique
--entidad.clave no puede ser porque son pocos registros.
CREATE INDEX PLACA_ENTIDAD_ID_IX ON PLACA(ENTIDAD_ID);
CREATE INDEX VEHICULO_MODELO_ID_IX ON VEHICULO(MODELO_ID);
CREATE INDEX VEHICULO_PROPIETARIO_ID_IX ON VEHICULO(PROPIETARIO_ID);
CREATE INDEX LICENCIA_PROPIETARIO_ID_IX ON LICENCIA(PROPIETARIO_ID);

-- Índices Unique (ya definidos en constraints, solo para referencia)
-- PROPIETARIO.RFC, PROPIETARIO.CURP, PROPIETARIO.EMAIL, VEHICULO.NUM_SERIE_VEHICULO,
-- vehiculo.NUM_SERIE_DISPOSITIVO.
CREATE UNIQUE INDEX PLACA_NUM_PLACA_IUX  ON PLACA(NUM_PLACA);

-- Índices compuestos
-- Ya definido: FALTA(FOLIO, PROPIETARIO_ID)
CREATE INDEX HISTORICO_PROPIETARIO_VEHICULO_VEHICULO_ID_PROPIETARIO_ID_IX 
    ON HISTORICO_PROPIETARIO_VEHICULO(PROPIETARIO_ID, VEHICULO_ID);
CREATE INDEX REPORTE_EMISIONES_GAS_ID_VEHICULO_ID_IX ON REPORTE_EMISIONES(GAS_ID, VEHICULO_ID);

-- Índices basados en funciones
--PONER FECHAS
