PROMPT creando sinonimos

CREATE OR REPLACE PUBLIC SYNONYM R_E_N FOR REPORTE_EMISIONES_NOTIFICACION;

CREATE OR REPLACE PUBLIC SYNONYM H_P_V FOR HISTORICO_PROPIETARIO_VEHICULO;

CREATE OR REPLACE PUBLIC SYNONYM R_V FOR REPORTE_VERIFICENTRO;

CREATE OR REPLACE PUBLIC SYNONYM H_E_V FOR HISTORICO_ESTATUS_VEHICULO;

PROMPT Otorgando permisos de lectura de entidades a &p_usuario_invitado

GRANT SELECT ON ESTATUS_VEHICULO TO &P_USUARIO_INVITADO;

GRANT SELECT ON MARCA TO &P_USUARIO_INVITADO;

GRANT SELECT ON MODELO TO &P_USUARIO_INVITADO;

GRANT SELECT ON VEHICULO TO &P_USUARIO_INVITADO;

GRANT SELECT ON REPORTE_EMISIONES_NOTIFICACION TO &P_USUARIO_INVITADO;

GRANT SELECT ON HISTORICO_PROPIETARIO_VEHICULO TO &P_USUARIO_INVITADO;

GRANT SELECT ON REPORTE_VERIFICENTRO TO &P_USUARIO_INVITADO;

GRANT SELECT ON HISTORICO_ESTATUS_VEHICULO TO &P_USUARIO_INVITADO;

GRANT SELECT ON REPORTE_EMISIONES TO &P_USUARIO_INVITADO;

GRANT SELECT ON ENTIDAD TO &P_USUARIO_INVITADO;

GRANT SELECT ON DE_CARGA TO &P_USUARIO_INVITADO;

GRANT SELECT ON TRANSPORTE_PUBLICO TO &P_USUARIO_INVITADO;

GRANT SELECT ON PARTICULAR TO &P_USUARIO_INVITADO;

GRANT SELECT ON GAS TO &P_USUARIO_INVITADO;

GRANT SELECT ON VERIFICACION TO &P_USUARIO_INVITADO;

GRANT SELECT ON FALTA TO &P_USUARIO_INVITADO;

GRANT SELECT ON NOTIFICACION TO &P_USUARIO_INVITADO;

DISCONNECT

CONNECT &P_USUARIO_INVITADO/&P_PASSWORD@&p_pdb

CREATE OR REPLACE SYNONYM S_ESTATUS_VEHICULO
FOR &P_USUARIO_ADMIN..ESTATUS_VEHICULO;

CREATE OR REPLACE SYNONYM S_MARCA
FOR &P_USUARIO_ADMIN..MARCA;

CREATE OR REPLACE SYNONYM S_MODELO
FOR &P_USUARIO_ADMIN..MODELO;

CREATE OR REPLACE SYNONYM S_VEHICULO
FOR &P_USUARIO_ADMIN..VEHICULO;

CREATE OR REPLACE SYNONYM S_REPORTE_EMISIONES_NOTIFICACION
FOR &P_USUARIO_ADMIN..REPORTE_EMISIONES_NOTIFICACION;

CREATE OR REPLACE SYNONYM S_HISTORICO_PROPIETARIO_VEHICULO
FOR &P_USUARIO_ADMIN..HISTORICO_PROPIETARIO_VEHICULO;

CREATE OR REPLACE SYNONYM S_HISTORICO_ESTATUS_VEHICULO
FOR &P_USUARIO_ADMIN..HISTORICO_ESTATUS_VEHICULO;

CREATE OR REPLACE SYNONYM S_REPORTE_EMISIONES
FOR &P_USUARIO_ADMIN..REPORTE_EMISIONES;

CREATE OR REPLACE SYNONYM S_REPORTE_VERIFICENTRO
FOR &P_USUARIO_ADMIN..REPORTE_EMISIONES;

CREATE OR REPLACE SYNONYM S_ENTIDAD
FOR &P_USUARIO_ADMIN..ENTIDAD;

CREATE OR REPLACE SYNONYM S_DE_CARGA
FOR &P_USUARIO_ADMIN..DE_CARGA;

CREATE OR REPLACE SYNONYM S_TRANSPORTE_PUBLICO
FOR &P_USUARIO_ADMIN..TRANSPORTE_PUBLICO;

CREATE OR REPLACE SYNONYM S_PARTICULAR
FOR &P_USUARIO_ADMIN..PARTICULAR;

CREATE OR REPLACE SYNONYM S_GAS
FOR &P_USUARIO_ADMIN..GAS;

CREATE OR REPLACE SYNONYM S_VERIFICACION
FOR &P_USUARIO_ADMIN..VERIFICACION;

CREATE OR REPLACE SYNONYM S_NOTIFICACION
FOR &P_USUARIO_ADMIN..NOTIFICACION;

CREATE OR REPLACE SYNONYM S_FALTA
FOR &P_USUARIO_ADMIN..FALTA;

DISCONNECT

connect &p_usuario_admin/&p_password@&p_pdb

prompt Ingrese las primeras letras del apellido paterno de cada integrante:

accept p_iniciales_apellidos default 'bc'

DECLARE
    V_TABLE_NAME   VARCHAR2(200);
    V_SYNONYM_NAME VARCHAR2(200);
    V_SQL          VARCHAR2(500);
    V_OWNER        VARCHAR2(50) := USER;
    V_PREFIX       VARCHAR2(10) := '&p_iniciales_apellidos';
BEGIN
    FOR TBL IN (
        SELECT
            OBJECT_NAME
        FROM
            USER_OBJECTS
        WHERE
            OBJECT_TYPE = 'TABLE'
    ) LOOP
        V_TABLE_NAME := TBL.OBJECT_NAME;
        V_SYNONYM_NAME := V_PREFIX
                          || '_'
                          || V_TABLE_NAME;
        V_SQL := 'CREATE OR REPLACE SYNONYM '
                 || V_SYNONYM_NAME
                 || ' FOR '
                 || V_OWNER
                 || '.'
                 || V_TABLE_NAME;
        EXECUTE IMMEDIATE V_SQL;
        DBMS_OUTPUT.PUT_LINE('Sinónimo creado: '
                             || V_SYNONYM_NAME
                             || ' para la tabla '
                             || V_TABLE_NAME);
    END LOOP;
END;
/

show errors;