CREATE OR REPLACE VIEW V_HISTORICO_ESTATUS_VEHICULOS AS
    SELECT
        V.VEHICULO_ID,
        V.NUM_SERIE_VEHICULO,
        E.DESCRIPCION        AS ESTATUS_ACTUAL,
        HE.FECHA_ESTATUS     AS FECHA_HISTORICA,
        EE.DESCRIPCION       AS ESTATUS_HISTORICO
    FROM
        VEHICULO                   V
        JOIN ESTATUS_VEHICULO E
        ON V.ESTATUS_VEHICULO_ID = E.ESTATUS_VEHICULO_ID
        JOIN HISTORICO_ESTATUS_VEHICULO HE
        ON HE.VEHICULO_ID = V.VEHICULO_ID
        JOIN ESTATUS_VEHICULO EE
        ON HE.ESTATUS_VEHICULO_ID = EE.ESTATUS_VEHICULO_ID;

CREATE OR REPLACE VIEW V_PROPIETARIOS_SIN_VEHICULO AS
    SELECT
        PR.NOMBRE,
        PR.AP_PATERNO,
        PR.AP_MATERNO,
        PR.RFC,
        VH.VEHICULO_ID
    FROM
        PROPIETARIO PR
        LEFT JOIN VEHICULO VH
        ON PR.PROPIETARIO_ID = VH.VEHICULO_ID
    WHERE
        VH.VEHICULO_ID = NULL;

CREATE OR REPLACE VIEW V_HISTORICO_ESTATUS_VEHICULOS AS
    SELECT
        V.VEHICULO_ID,
        V.NUM_SERIE_VEHICULO,
        HEV.FECHA_ESTATUS,
        EV.DESCRIPCION,       
        EV.CLAVE
    FROM
        VEHICULO                   V
        JOIN HISTORICO_ESTATUS_VEHICULO HEV
        ON HEV.VEHICULO_ID = V.VEHICULO_ID
        JOIN ESTATUS_VEHICULO EV
        ON HEV.ESTATUS_VEHICULO_ID = EV.ESTATUS_VEHICULO_ID;

CREATE OR REPLACE VIEW V_NUM_VEHICULOS_DEL_PROPIETARIO_HISTORICO AS
    SELECT
        PR.NOMBRE,
        PR.AP_PATERNO,
        PR.AP_MATERNO,
        PR.RFC,
        COUNT(*)      NUM_VEHICULOS
    FROM
        PROPIETARIO                    PR
        JOIN HISTORICO_PROPIETARIO_VEHICULO HPV
        ON PR.PROPIETARIO_ID = HPV.PROPIETARIO_ID
    GROUP BY
        PR.NOMBRE,
        PR.AP_PATERNO,
        PR.AP_MATERNO,
        PR.RFC;
