/*
@Autor:           Belmont Muñoz Samuel
                  Capistrán Manuel
@Fecha creación:  dd/mm/yyyy
@Descripción:     s9
*/

--
--ENTIDAD
--
INSERT INTO ENTIDAD(ENTIDAD_ID,NOMBRE,CLAVE) VALUES(SEQ_ENTIDAD_ID.nextval, 'CIUDAD DE MEXICO','CDMX');
INSERT INTO ENTIDAD(ENTIDAD_ID,NOMBRE,CLAVE) VALUES(SEQ_ENTIDAD_ID.nextval, 'PUEBLA','PUE');


--
--PLACA
--
INSERT INTO PLACA(PLACA_ID,ES_ACTIVA,NUM_PLACA,FECHA_ASIGNACION,ENTIDAD_ID) VALUES(SEQ_PLACA_ID.nextval,1,'RCN205D',TO_DATE('2010/01/01','YYYY/MM/DD'),1001);
INSERT INTO PLACA(PLACA_ID,ES_ACTIVA,NUM_PLACA,FECHA_ASIGNACION,ENTIDAD_ID) VALUES(SEQ_PLACA_ID.nextval,1,'PBV8004',TO_DATE('2007/01/01','YYYY/MM/DD'),1001);
INSERT INTO PLACA(PLACA_ID,ES_ACTIVA,NUM_PLACA,FECHA_ASIGNACION,ENTIDAD_ID) VALUES(SEQ_PLACA_ID.nextval,1,'T26ATA', TO_DATE('2004/01/01','YYYY/MM/DD'),1001);
INSERT INTO PLACA(PLACA_ID,ES_ACTIVA,NUM_PLACA,FECHA_ASIGNACION,ENTIDAD_ID) VALUES(SEQ_PLACA_ID.nextval,1,'123ABC', TO_DATE('2003/11/23','YYYY/MM/DD'),1002);
INSERT INTO PLACA(PLACA_ID,ES_ACTIVA,NUM_PLACA,FECHA_ASIGNACION,ENTIDAD_ID) VALUES(SEQ_PLACA_ID.nextval,0,'MRR647A',TO_DATE('2008/11/30','YYYY/MM/DD'),1002);


--
--PROPIETARIO
--
INSERT INTO PROPIETARIO(PROPIETARIO_ID,NOMBRE,AP_MATERNO,RFC,CURP,AP_PATERNO,EMAIL) VALUES(SEQ_PROPIETARIO_ID.nextval,'MANUEL','PONCE','CAPM020110SI3','CAPM020110HDFPNNA3','CAPISTRAN','MANUELECAPISTRAN@GMAIL.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID,NOMBRE,AP_MATERNO,RFC,CURP,AP_PATERNO,EMAIL) VALUES(SEQ_PROPIETARIO_ID.nextval,'FERNANDA','DIAZ','SADR050510MDF',NULL,'SANCHEZ','FERNISAENZ16@GMAIL.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID,NOMBRE,AP_MATERNO,RFC,CURP,AP_PATERNO,EMAIL) VALUES(SEQ_PROPIETARIO_ID.nextval,'REBECA','DIAZ','SADF030421MDF',NULL,'SANCHEZ','REBECA.SAENZ.DIAZ@GMAIL.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID,NOMBRE,AP_MATERNO,RFC,CURP,AP_PATERNO,EMAIL) VALUES(SEQ_PROPIETARIO_ID.nextval,'JORGE','GUTIERREZ','SAGJ680107SP1','SAGJ680107HDFPMN4','SANCHEZ','JORGESPEJOS@HOTMAIL.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID,NOMBRE,AP_MATERNO,RFC,CURP,AP_PATERNO,EMAIL) VALUES(SEQ_PROPIETARIO_ID.nextval,'KARIS','GONZALEZ','DIGK750530CZ6','DIGK750530MDFPMN5','DIAZ','PSIC.KARINADIAZ@GMAIL.COM');


--
--LICENCIA
--
INSERT INTO LICENCIA(LICENCIA_ID,LICENCIA_ANTERIOR_ID,)












