
CREATE OR REPLACE TRIGGER TR_INSERTAR_LICENCIA FOR
    INSERT ON LICENCIA
COMPOUND TRIGGER
    TYPE LICENCIA_TYPE IS RECORD(
        LICENCIA_ID LICENCIA.LICENCIA_ID%TYPE,
        PROPIETARIO_ID LICENCIA.PROPIETARIO_ID%TYPE,
        FECHA_EMISION LICENCIA.FECHA_EMISION%TYPE,
        TIPO LICENCIA.TIPO%TYPE
    );
    TYPE LICENCIAS_TYPE IS
        TABLE OF LICENCIA_TYPE;
    LICENCIAS LICENCIAS_TYPE := LICENCIAS_TYPE();
    BEFORE EACH ROW IS
        V_INDEX NUMBER;
    BEGIN
        LICENCIAS.EXTEND;
        V_INDEX:=LICENCIAS.LAST;
        LICENCIAS(V_INDEX).LICENCIA_ID := :NEW.LICENCIA_ID;
        LICENCIAS(V_INDEX).PROPIETARIO_ID := :NEW.PROPIETARIO_ID;
        LICENCIAS(V_INDEX).FECHA_EMISION := :NEW.FECHA_EMISION;
        LICENCIAS(V_INDEX).TIPO := :NEW.TIPO;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
        V_DERECHO_LICENCIA PROPIETARIO.DERECHO_LICENCIA%TYPE;
        V_NUM_LICENCIAS_VIGENTES    NUMBER;
    BEGIN
        FOR I IN LICENCIAS.FIRST .. LICENCIAS.LAST LOOP
           IF LICENCIAS(I).FECHA_EMISION <= SYSDATE THEN
                SELECT
                    DERECHO_LICENCIA INTO V_DERECHO_LICENCIA
                FROM
                    PROPIETARIO
                WHERE
                    PROPIETARIO_ID = LICENCIAS(I).PROPIETARIO_ID;

                SELECT
                    COUNT(*) INTO V_NUM_LICENCIAS_VIGENTES
                FROM
                    LICENCIA
                WHERE
                    PROPIETARIO_ID = LICENCIAS(I).PROPIETARIO_ID
                    AND TIPO = LICENCIAS(I).TIPO
                    AND TO_CHAR(FECHA_VENCIMIENTO, 'YYYYMM') >= TO_CHAR(LICENCIAS(I).FECHA_EMISION, 'YYYYMM');

                IF V_DERECHO_LICENCIA = FALSE THEN 
                    DBMS_OUTPUT.PUT_LINE('EL PROPIETARIO NO TIENE DERECHO A LICENCIA');
                    DELETE LICENCIA
                    WHERE LICENCIA_ID = LICENCIAS(I).LICENCIA_ID;
                ELSIF V_NUM_LICENCIAS_VIGENTES >1 THEN
                    DBMS_OUTPUT.PUT_LINE('EL PROPIETARIO YA CUENTA CON ESTE TIPO DE LICENCIA AÚN VIGENTE');
                    DELETE LICENCIA
                    WHERE LICENCIA_ID = LICENCIAS(I).LICENCIA_ID;
                END IF; 
            ELSE
                DBMS_OUTPUT.PUT_LINE('EL PROPIETARIO NO PUEDE INSERTAR LICENCIAS PARA EL FUTURO');
                DELETE LICENCIA
                WHERE LICENCIA_ID = LICENCIAS(I).LICENCIA_ID;
            END IF;
        END LOOP;
    END AFTER STATEMENT;
END;
/
SHOW ERRORS;
