
CREATE OR REPLACE TRIGGER TR_INSERTAR_TRANSPORTE_PUBLICO BEFORE
    INSERT ON TRANSPORTE_PUBLICO FOR EACH ROW
DECLARE
    V_NUM_LICENCIAS NUMBER;
BEGIN
    SELECT
        COUNT(*) INTO V_NUM_LICENCIAS
    FROM
        LICENCIA LIC
        JOIN PROPIETARIO PR
        ON LIC.PROPIETARIO_ID = PR.PROPIETARIO_ID
        JOIN VEHICULO VH
        ON VH.PROPIETARIO_ID = PR.PROPIETARIO_ID
    WHERE
        VH.VEHICULO_ID = :NEW.VEHICULO_ID
    AND
        LIC.TIPO = :NEW.TIPO_LICENCIA_REQ;

    IF V_NUM_LICENCIAS = 0 THEN
            RAISE_APPLICATION_ERROR(-20004, 'EL PROPIETARIO NO CUENTA CON LA LICENCIA ADECUADA PARA ESTE VEHICULO DE TRANSPORTE PÚBLICO');
    END IF;
END;
/
SHOW ERRORS;