
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt INSERTAR LICENCIA EXITOSAMENTE 
PROMPT 0 LICENCIAS REGISTRADAS POR PARTE DEL PROPIETARIO
Prompt ========================================

DECLARE
V_NUM_REGISTROS NUMBER;
BEGIN
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
    NUM_LICENCIA, TIPO, FECHA_EMISION, PROPIETARIO_ID, ES_ACTIVA)
VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE, 1002, TRUE);

SELECT COUNT(*) INTO V_NUM_REGISTROS
FROM LICENCIA
WHERE PROPIETARIO_ID = 1002;
IF V_NUM_REGISTROS = 1 THEN
    DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
ELSE 
    DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
END IF; 
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;


Prompt =======================================
Prompt Prueba 2.
prompt INSERTAR LICENCIA EXITOSAMENTE 
PROMPT 1 LICENCIA EXPIRADA REGISTRADA POR PARTE DEL PROPIETARIO
Prompt ========================================

DECLARE
V_NUM_REGISTROS NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE-5000,1002, TRUE);
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10002, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10002', 'A', SYSDATE,1002, TRUE);
   
    SELECT COUNT(*) INTO V_NUM_REGISTROS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND TIPO = 'A';
    IF V_NUM_REGISTROS = 2 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;

SELECT * FROM LICENCIA;

Prompt =======================================
Prompt Prueba 3.
prompt INSERTAR LICENCIA SIN ÉXITO 
PROMPT PROPIETARIO SIN DERECHO_LICENCIA
Prompt ========================================

DECLARE
V_NUM_REGISTROS NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE-3000,1002, TRUE);
    
    UPDATE PROPIETARIO SET
    DERECHO_LICENCIA = FALSE
    WHERE PROPIETARIO_ID = 1002;

    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10002, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10002', 'A', SYSDATE,1002, TRUE); 
    SELECT COUNT(*) INTO V_NUM_REGISTROS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND TIPO = 'A';
    IF V_NUM_REGISTROS = 1  THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;    
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 4.
prompt INSERTAR LICENCIA SIN ÉXITO
PROMPT AÚN NO HA EXPIRADO SU LICENCIA
Prompt ========================================


DECLARE
V_NUM_REGISTROS NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE-10,1002, TRUE);
    
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10002, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10002', 'A', SYSDATE,1002, TRUE);
   
    SELECT COUNT(*) INTO V_NUM_REGISTROS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND TIPO = 'A';
    IF V_NUM_REGISTROS = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;  
END;
/       
ROLLBACK;
COMMIT;
SHOW ERRORS;


Prompt =======================================
Prompt Prueba 5.
prompt INSERTAR LICENCIA SIN ÉXITO
PROMPT VIAJERO EN EL TIEMPO
Prompt ========================================


DECLARE
V_NUM_REGISTROS NUMBER;

BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE+100,1002, TRUE);
    
    SELECT COUNT(*) INTO V_NUM_REGISTROS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND TIPO = 'A';
    IF V_NUM_REGISTROS = 0 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;  
END;
/       
ROLLBACK;
COMMIT;
SHOW ERRORS;




