
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);

INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
    NUM_LICENCIA, TIPO, FECHA_EMISION,PROPIETARIO_ID, ES_ACTIVA)
VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE,1002, TRUE),
      (10002, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10002', 'B', SYSDATE,1002, TRUE),
      (10003, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10003', 'C', SYSDATE,1002, TRUE);


INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
VALUES (1001, '1ABC123', TRUE, SYSDATE, 32);
INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
VALUES (1002, '2DEF456', TRUE, SYSDATE, 17);
INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
VALUES (1003, '3GHI789', TRUE, SYSDATE, 16);

INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
VALUES (1001, 'SERIE1001', SYSDATE, FALSE, TRUE, FALSE, 'SERIEV1001', 1, 1002, 1, 1001);
INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
VALUES (1002, 'SERIE1002', SYSDATE, FALSE, TRUE, FALSE, 'SERIEV1002', 2, 1002, 1, 1002);
INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
VALUES (1003, 'SERIE1003', SYSDATE, FALSE, TRUE, FALSE, 'SERIEV1003', 3, 1002, 1, 1003);
SAVEPOINT SV1;
Prompt =======================================
Prompt Prueba 1.
prompt INSERTAR VEHICULOS DE CADA TIPO DE TRANSPORTE PÚBLICO
PROMPT 
Prompt ========================================

DECLARE
V_NUM_TRANSPORTES_P NUMBER;
BEGIN
    
    INSERT INTO TRANSPORTE_PUBLICO(VEHICULO_ID, TIPO_TRANSPORTE_PUBLICO, TIPO_LICENCIA_REQ,
        PASAJEROS_SENTADOS, PASAJEROS_PARADOS)
    VALUES(1001, 'T', 'A', 4, 0), (1002, 'V', 'B', 10, 0), (1003, 'A', 'C', 20, 20);
    

    SELECT COUNT(*) INTO V_NUM_TRANSPORTES_P
    FROM TRANSPORTE_PUBLICO TP
    JOIN VEHICULO VH ON TP.VEHICULO_ID = VH.VEHICULO_ID
    WHERE VH.PROPIETARIO_ID = 1002;

    IF V_NUM_TRANSPORTES_P = 3 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/
ROLLBACK TO SV1;

Prompt =======================================
Prompt Prueba 2.
prompt INSERTAR AUTOBUS SIN LICENCIA TIPO C
PROMPT 
Prompt ========================================

DECLARE
V_NUM_TRANSPORTES_P NUMBER;
V_EXCEPTION VARCHAR2(20);
BEGIN
    DELETE LICENCIA
    WHERE LICENCIA_ID = 10003;
    INSERT INTO TRANSPORTE_PUBLICO(VEHICULO_ID, TIPO_TRANSPORTE_PUBLICO, TIPO_LICENCIA_REQ,
        PASAJEROS_SENTADOS, PASAJEROS_PARADOS)
    VALUES (1003, 'A', 'C', 20, 20);
    DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    EXCEPTION
        WHEN OTHERS THEN
            SELECT COUNT(*) INTO V_NUM_TRANSPORTES_P
            FROM TRANSPORTE_PUBLICO TP
            JOIN VEHICULO VH ON TP.VEHICULO_ID = VH.VEHICULO_ID
            WHERE VH.PROPIETARIO_ID = 1002;
            V_EXCEPTION := ''||SQLCODE;
            IF V_NUM_TRANSPORTES_P = 0  THEN
                DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
            ELSE 
                DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
            END IF; 

    
END;
/
ROLLBACK TO SV1;


Prompt =======================================
Prompt Prueba 3.
prompt INSERTAR VAN SIN LICENCIA TIPO B
PROMPT 
Prompt ========================================

DECLARE
V_NUM_TRANSPORTES_P NUMBER;
V_EXCEPTION VARCHAR2(20);
BEGIN
    DELETE LICENCIA
    WHERE LICENCIA_ID = 10002;
    INSERT INTO TRANSPORTE_PUBLICO(VEHICULO_ID, TIPO_TRANSPORTE_PUBLICO, TIPO_LICENCIA_REQ,
        PASAJEROS_SENTADOS, PASAJEROS_PARADOS)
    VALUES(1002, 'V', 'B', 10, 0);
    DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    EXCEPTION
        WHEN OTHERS THEN
            SELECT COUNT(*) INTO V_NUM_TRANSPORTES_P
            FROM TRANSPORTE_PUBLICO TP
            JOIN VEHICULO VH ON TP.VEHICULO_ID = VH.VEHICULO_ID
            WHERE VH.PROPIETARIO_ID = 1002;
            V_EXCEPTION := ''||SQLCODE;
            IF V_NUM_TRANSPORTES_P = 0  THEN
                DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
            ELSE 
                DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
            END IF; 
    
END;
/
ROLLBACK TO SV1;


Prompt =======================================
Prompt Prueba 4.
prompt INSERTAR TAXI SIN LICENCIA TIPO A
PROMPT 
Prompt ========================================

DECLARE
V_NUM_TRANSPORTES_P NUMBER;
V_EXCEPTION VARCHAR2(20);
BEGIN
    DELETE LICENCIA
    WHERE LICENCIA_ID = 10001;
    INSERT INTO TRANSPORTE_PUBLICO(VEHICULO_ID, TIPO_TRANSPORTE_PUBLICO, TIPO_LICENCIA_REQ,
        PASAJEROS_SENTADOS, PASAJEROS_PARADOS)
    VALUES(1001, 'T', 'A', 4, 0);
    DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    EXCEPTION
        WHEN OTHERS THEN
            SELECT COUNT(*) INTO V_NUM_TRANSPORTES_P
            FROM TRANSPORTE_PUBLICO TP
            JOIN VEHICULO VH ON TP.VEHICULO_ID = VH.VEHICULO_ID
            WHERE VH.PROPIETARIO_ID = 1002;
            V_EXCEPTION := ''||SQLCODE;
            IF V_NUM_TRANSPORTES_P = 0  THEN
                DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
            ELSE 
                DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
            END IF; 
    
END;
/
ROLLBACK;
SHOW ERRORS;