
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt INSERTAR PUNTOS NEGATIVOS CON SUMA MENOR DE 200 PUNTOS
PROMPT SIGUE TENIENDO DERECHO A LICENCIA Y SUS LICENCIAS ESTÁN ACTIVAS
Prompt ========================================

DECLARE
V_DERECHO_LICENCIA PROPIETARIO.DERECHO_LICENCIA%TYPE;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    PR_INSERTAR_FALTA(1002,SYSDATE,'FALTA 1',100,EMPTY_CLOB());
    SELECT DERECHO_LICENCIA INTO V_DERECHO_LICENCIA
    FROM PROPIETARIO
    WHERE PROPIETARIO_ID = 1002;
    IF V_DERECHO_LICENCIA = TRUE THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/

ROLLBACK;
COMMIT;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 2.
prompt INSERTAR PUNTOS NEGATIVOS CON SUMA MAYOR O IGUAL DE 200 PUNTOS
PROMPT NO TIENE DERECHO A LICENCIA Y SE DESACTIVAN LICENCIAS
Prompt ========================================

DECLARE
V_DERECHO_LICENCIA PROPIETARIO.DERECHO_LICENCIA%TYPE;
V_LICENCIAS_ACTIVAS NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ,
        NUM_LICENCIA, TIPO, FECHA_EMISION, PROPIETARIO_ID, ES_ACTIVA)
    VALUES(10001, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), '10001', 'A', SYSDATE, 1002, TRUE);

    PR_INSERTAR_FALTA(1002,SYSDATE,'FALTA 1',100,EMPTY_CLOB());
    PR_INSERTAR_FALTA(1002,SYSDATE,'FALTA 2',50,EMPTY_CLOB());
    PR_INSERTAR_FALTA(1002,SYSDATE,'FALTA 3',70,EMPTY_CLOB());

    SELECT DERECHO_LICENCIA INTO V_DERECHO_LICENCIA
    FROM PROPIETARIO
    WHERE PROPIETARIO_ID = 1002;

    SELECT COUNT(*) INTO V_LICENCIAS_ACTIVAS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND ES_ACTIVA = TRUE;


    IF V_DERECHO_LICENCIA = FALSE AND V_LICENCIAS_ACTIVAS = 0  THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;



