
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);

INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
VALUES (1001, '1ABC123', TRUE, SYSDATE, 32);
INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
VALUES (1002, '2DEF456', TRUE, SYSDATE, 17);
INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
VALUES (1003, '3GHI789', TRUE, SYSDATE, 16);

INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
VALUES (1001, 'SERIE1001', SYSDATE, FALSE, TRUE, FALSE, 'SERIEV1001', 1, 1002, 1, 1001);
INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
VALUES (1002, 'SERIE1002', SYSDATE, FALSE, TRUE, FALSE, 'SERIEV1002', 2, 1002, 1, 1002);
INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
VALUES (1003, 'SERIE1003', SYSDATE, FALSE, TRUE, FALSE, 'SERIEV1003', 3, 1002, 1, 1003);
SAVEPOINT SV1;
Prompt =======================================
Prompt Prueba 1.
prompt INSERTAR REPORTES DE EMISIONES POR CADA
PROMPT GAS DE UN VEHICULO SIN NOTIFICACION
Prompt ========================================
DECLARE
V_NUM_NOTIFICACIONES NUMBER;
BEGIN
    INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, FECHA_REGISTRO,
        VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
    VALUES(1001, SYSDATE, 0.1, 1, 1001),
          (1002, SYSDATE, 0.1, 2, 1001),
          (1003, SYSDATE, 0.1, 3, 1001),
          (1004, SYSDATE, 0.1, 4, 1001);

    SELECT COUNT(*) INTO V_NUM_NOTIFICACIONES
    FROM (
        SELECT NT.NOTIFICACION_ID
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        JOIN VEHICULO VH
            ON VH.VEHICULO_ID = RE.VEHICULO_ID
        WHERE RE.VEHICULO_ID = 1001
        GROUP BY NT.NOTIFICACION_ID
    );
    IF V_NUM_NOTIFICACIONES = 0 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
END;
/
ROLLBACK TO SV1;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 2.
prompt INSERTAR REPORTES DE EMISIONES POR CADA
PROMPT GAS DE UN VEHICULO CON NOTIFICACION
Prompt ========================================
DECLARE
V_NUM_NOTIFICACIONES NUMBER;
V_NUM_REPORTES_EMISIONES_NOTIFICACION NUMBER;
BEGIN
    INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, FECHA_REGISTRO,
        VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
    VALUES(1001, SYSDATE, 0.9, 1, 1001),
          (1002, SYSDATE, 0.1, 2, 1001),
          (1003, SYSDATE, 0.9, 3, 1001),
          (1004, SYSDATE, 0.1, 4, 1001);

    SELECT COUNT(*) INTO V_NUM_NOTIFICACIONES
    FROM (
        SELECT NT.NOTIFICACION_ID
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        JOIN VEHICULO VH
            ON VH.VEHICULO_ID = RE.VEHICULO_ID
        WHERE RE.VEHICULO_ID = 1001
        GROUP BY NT.NOTIFICACION_ID
    );
    SELECT COUNT(*) INTO V_NUM_REPORTES_EMISIONES_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    JOIN VEHICULO VH
        ON VH.VEHICULO_ID = RE.VEHICULO_ID
    WHERE RE.VEHICULO_ID = 1001;

    IF V_NUM_NOTIFICACIONES = 1 
        AND V_NUM_REPORTES_EMISIONES_NOTIFICACION = 2 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
END;
/
ROLLBACK TO SV1;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 3.
prompt INSERTAR REPORTES DE EMISIONES EN DIFERENTES DIAS POR CADA
PROMPT GAS DE UN VEHICULO CON NOTIFICACION
Prompt ========================================
DECLARE
V_NUM_NOTIFICACIONES NUMBER;
V_NUM_REPORTES_EMISIONES_NOTIFICACION NUMBER;
BEGIN
    INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, FECHA_REGISTRO,
        VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
    VALUES(1001, SYSDATE, 0.9, 1, 1001),
          (1002, SYSDATE+100, 0.9, 2, 1001),
          (1003, SYSDATE+200, 0.9, 3, 1001),
          (1004, SYSDATE+300, 0.9, 4, 1001);
    SELECT COUNT(*) INTO V_NUM_NOTIFICACIONES
    FROM (
        SELECT NT.NOTIFICACION_ID
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        JOIN VEHICULO VH
            ON VH.VEHICULO_ID = RE.VEHICULO_ID
        WHERE RE.VEHICULO_ID = 1001
        GROUP BY NT.NOTIFICACION_ID
    );
    SELECT COUNT(*) INTO V_NUM_REPORTES_EMISIONES_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    JOIN VEHICULO VH
        ON VH.VEHICULO_ID = RE.VEHICULO_ID
    WHERE RE.VEHICULO_ID = 1001;

    IF V_NUM_NOTIFICACIONES = 4  THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
END;
/
ROLLBACK TO SV1;
SHOW ERRORS;
ROLLBACK;