
CREATE OR REPLACE PROCEDURE PR_INSERTAR_LICENCIA(
    P_FOTO IN LICENCIA.FOTO%TYPE,
    P_FIRMA IN LICENCIA.FIRMA%TYPE,
    P_HUELLA_INDICE_DER IN LICENCIA.HUELLA_INDICE_DER%TYPE,
    P_HUELLA_INDICE_IZQ IN LICENCIA.HUELLA_INDICE_IZQ%TYPE,
    P_FECHA_EMISION IN LICENCIA.FECHA_EMISION%TYPE,
    P_NUM_LICENCIA IN LICENCIA.NUM_LICENCIA%TYPE,
    P_TIPO IN LICENCIA.TIPO%TYPE,
    P_PROPIETARIO_ID IN LICENCIA.PROPIETARIO_ID%TYPE
) IS
V_LICENCIA_ANTERIOR_ID LICENCIA.LICENCIA_ANTERIOR_ID%TYPE;
V_NUM_LICENCIAS NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_NUM_LICENCIAS
    FROM LICENCIA
    WHERE FECHA_VENCIMIENTO = (
        SELECT MAX(FECHA_VENCIMIENTO)
        FROM LICENCIA
        WHERE PROPIETARIO_ID = P_PROPIETARIO_ID
        AND TIPO = P_TIPO
    )
    AND PROPIETARIO_ID = P_PROPIETARIO_ID
    AND TIPO = P_TIPO;

    IF V_NUM_LICENCIAS = 1 THEN
        SELECT LICENCIA_ID INTO V_LICENCIA_ANTERIOR_ID
        FROM LICENCIA
        WHERE FECHA_VENCIMIENTO = (
            SELECT MAX(FECHA_VENCIMIENTO)
            FROM LICENCIA
            WHERE PROPIETARIO_ID = P_PROPIETARIO_ID
            AND TIPO = P_TIPO
        )
        AND PROPIETARIO_ID = P_PROPIETARIO_ID
        AND TIPO = P_TIPO;
        INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ, FECHA_EMISION,NUM_LICENCIA, TIPO, PROPIETARIO_ID, LICENCIA_ANTERIOR_ID)
        VALUES(LICENCIA_SEQ.NEXTVAL, P_FOTO, P_FIRMA, P_HUELLA_INDICE_DER, P_HUELLA_INDICE_IZQ, P_FECHA_EMISION,P_NUM_LICENCIA, P_TIPO, P_PROPIETARIO_ID, V_LICENCIA_ANTERIOR_ID);
        UPDATE LICENCIA SET
        ES_ACTIVA = FALSE
        WHERE LICENCIA_ID = V_LICENCIA_ANTERIOR_ID;
    ELSE
        INSERT INTO LICENCIA(LICENCIA_ID, FOTO, FIRMA, HUELLA_INDICE_DER, HUELLA_INDICE_IZQ, FECHA_EMISION,NUM_LICENCIA, TIPO, PROPIETARIO_ID, LICENCIA_ANTERIOR_ID)
        VALUES(LICENCIA_SEQ.NEXTVAL, P_FOTO, P_FIRMA, P_HUELLA_INDICE_DER, P_HUELLA_INDICE_IZQ, P_FECHA_EMISION,P_NUM_LICENCIA, P_TIPO, P_PROPIETARIO_ID, NULL);
    END IF;
END;
/
SHOW ERRORS;
