CREATE OR REPLACE PROCEDURE PR_ACTUALIZAR_ESTATUS_VERIF_APROBADA(
    P_VERIFICACION_ID IN VERIFICACION.VERIFICACION_ID%TYPE
)IS
V_FECHA_VERIFICACION VERIFICACION.FECHA_VERIFICACION%TYPE;
V_FECHA_ESTATUS_VEHICULO VEHICULO.FECHA_ESTATUS%TYPE;
V_VEHICULO_ID VERIFICACION.VEHICULO_ID%TYPE;
V_ESTATUS_VEHICULO_ID VEHICULO.ESTATUS_VEHICULO_ID%TYPE;
V_VALOR_PERMITIDO GAS.NIVELES_PERMITIDOS%TYPE;
CURSOR CUR_REPORTES_VERIFICACION IS
SELECT GAS_ID, VALOR_MEDIDO
FROM REPORTE_VERIFICENTRO
WHERE VERIFICACION_ID = P_VERIFICACION_ID;

BEGIN
    SELECT VR.FECHA_VERIFICACION, VR.VEHICULO_ID, VH.FECHA_ESTATUS, VH.ESTATUS_VEHICULO_ID 
        INTO V_FECHA_VERIFICACION, V_VEHICULO_ID, V_FECHA_ESTATUS_VEHICULO, V_ESTATUS_VEHICULO_ID
    FROM VERIFICACION VR
    JOIN VEHICULO VH ON VH.VEHICULO_ID = VR.VEHICULO_ID
    WHERE VERIFICACION_ID = P_VERIFICACION_ID;

    IF V_ESTATUS_VEHICULO_ID <> 4 THEN
        RAISE_APPLICATION_ERROR(-20005, 'NO SE PUDO CAMBIAR EL ESTATUS DEL VEHICULO PORQUE NO TIENE VERIFICACION PENDIENTE');
        RETURN;
    ELSE 
        IF V_FECHA_VERIFICACION <= V_FECHA_ESTATUS_VEHICULO THEN
            RAISE_APPLICATION_ERROR(-20006, 'ESTA VERIFICACION NO CORRESPONDE A LA VERIFICACION PENDIENTE DEL VEHICULO');
            RETURN;
        ELSE
            FOR I IN CUR_REPORTES_VERIFICACION LOOP
                SELECT NIVELES_PERMITIDOS INTO V_VALOR_PERMITIDO
                FROM GAS G
                WHERE G.GAS_ID = I.GAS_ID;
                IF I.VALOR_MEDIDO > V_VALOR_PERMITIDO THEN
                    DBMS_OUTPUT.PUT_LINE('NO SE PUDO CAMBIAR EL ESTATUS DE VERIFICACION PENDIENTE'||
                    ' POR NIVELES ALTOS DEL GAS: ' || I.GAS_ID ||' VALOR PERMITIDO: '||V_VALOR_PERMITIDO||' VALOR MEDIDO: ' ||I.VALOR_MEDIDO);
                    RETURN;    
                END IF;
            END LOOP;
            UPDATE VEHICULO SET 
                ESTATUS_VEHICULO_ID = 1,
                FECHA_ESTATUS = SYSDATE
            WHERE VEHICULO_ID = V_VEHICULO_ID;
            DBMS_OUTPUT.PUT_LINE('SE CAMBIO CON ÉXITO EL ESTATUS A -EN REGLA-');
        END IF;
    END IF;
    

END;
/
SHOW ERRORS;