
CREATE OR REPLACE PROCEDURE PR_INSERTAR_NOTIFICACION(
    P_FECHA_ENVIO IN DATE,
    P_VEHICULO_ID IN NUMBER,
    P_NOTIFICACION_ID OUT NUMBER
) IS
V_NUM_NOTIFICACION NOTIFICACION.NUM_NOTIFICACION%TYPE;
V_PROPIETARIO_ID PROPIETARIO.PROPIETARIO_ID%TYPE;
BEGIN
    SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUM_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN 
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE 
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    WHERE RE.VEHICULO_ID = P_VEHICULO_ID;

    INSERT INTO NOTIFICACION(NOTIFICACION_ID, NUM_NOTIFICACION, FECHA_ENVIO)
    VALUES(NOTIFICACION_SEQ.NEXTVAL, V_NUM_NOTIFICACION + 1, P_FECHA_ENVIO);
    SELECT NOTIFICACION_SEQ.CURRVAL INTO P_NOTIFICACION_ID FROM DUAL;
END;
/
SHOW ERRORS;