
CREATE OR REPLACE PROCEDURE PR_INSERTAR_FALTA(
    P_PROPIETARIO_ID IN FALTA.PROPIETARIO_ID%TYPE,
    P_FECHA IN FALTA.FECHA%TYPE,
    P_DESCRIPCION IN FALTA.DESCRIPCION%TYPE,
    P_CANTIDAD_PUNTOS_NEGATIVOS IN FALTA.CANTIDAD_PUNTOS_NEGATIVOS%TYPE,
    P_DETALLE_FALTA IN FALTA.DETALLE_FALTA%TYPE
) IS
V_FOLIO FALTA.FOLIO%TYPE;
BEGIN
    SELECT NVL(MAX(FOLIO),0) INTO V_FOLIO
    FROM FALTA F
    WHERE F.PROPIETARIO_ID = P_PROPIETARIO_ID;

    INSERT INTO FALTA(FOLIO, PROPIETARIO_ID, FECHA, DESCRIPCION, CANTIDAD_PUNTOS_NEGATIVOS, DETALLE_FALTA)
    VALUES(V_FOLIO + 1, P_PROPIETARIO_ID, P_FECHA, P_DESCRIPCION, P_CANTIDAD_PUNTOS_NEGATIVOS, P_DETALLE_FALTA);
END;
/
SHOW ERRORS;