
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF

Prompt =======================================
Prompt Prueba 1.
prompt Insertando notificaciones para un mismo vehiculo
Prompt ========================================


SELECT REPORTE_EMISIONES_SEQ.NEXTVAL FROM DUAL;
SELECT NOTIFICACION_SEQ.NEXTVAL FROM DUAL;

DECLARE
V_NOTIFICACION_ID NUMBER;
V_CURRVAL_NOTIFICACION NUMBER;
V_NUM_NOTIFICACION NUMBER;
V_NUEVO_NUM_NOTIFICACION NUMBER;
V_REPORTE_EMISIONES_ID NUMBER;
V_CURRVAL_REPORTE_EMISIONES NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
    VALUES (1001, '1ABC123', TRUE, SYSDATE, 32);
    INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
    VALUES (1001, 'SERIE001', SYSTIMESTAMP, FALSE, FALSE, TRUE, 'SERIEV001', 1, 1002, 4, 1001);

    SELECT NOTIFICACION_SEQ.CURRVAL INTO V_CURRVAL_NOTIFICACION 
    FROM DUAL;
    SELECT REPORTE_EMISIONES_SEQ.CURRVAL INTO V_CURRVAL_REPORTE_EMISIONES
    FROM DUAL;

    SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUM_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN 
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE 
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    WHERE RE.VEHICULO_ID = 1001;
    
    FOR I IN 1..10 LOOP
        
        SELECT REPORTE_EMISIONES_SEQ.NEXTVAL INTO V_REPORTE_EMISIONES_ID FROM DUAL;

        INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, 
            FECHA_REGISTRO, VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
        VALUES(V_REPORTE_EMISIONES_ID, SYSDATE + I+1, 0.9, 1, 1001);

        PR_INSERTAR_NOTIFICACION(SYSDATE + I, 1001,V_NOTIFICACION_ID);

        INSERT INTO REPORTE_EMISIONES_NOTIFICACION(REPORTE_EMISIONES_ID,
            NOTIFICACION_ID)
        VALUES(V_REPORTE_EMISIONES_ID, V_NOTIFICACION_ID);
    END LOOP;
    

    SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUEVO_NUM_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN 
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE 
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    WHERE RE.VEHICULO_ID = 1001; 


    IF V_NUEVO_NUM_NOTIFICACION - V_NUM_NOTIFICACION = 10 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
    ROLLBACK;
    EXECUTE IMMEDIATE 'DROP SEQUENCE NOTIFICACION_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE NOTIFICACION_SEQ
                        START WITH ' || v_currval_notificacion || '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE REPORTE_EMISIONES_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE REPORTE_EMISIONES_SEQ
                        START WITH ' || V_CURRVAL_REPORTE_EMISIONES|| '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    
END;
/

SHOW ERRORS;

Prompt =======================================
Prompt Prueba 2.
prompt Insertando notificaciones para diferentes vehiculos
Prompt ========================================


SELECT REPORTE_EMISIONES_SEQ.NEXTVAL FROM DUAL;
SELECT NOTIFICACION_SEQ.NEXTVAL FROM DUAL;

DECLARE
V_NOTIFICACION_ID NUMBER;
V_CURRVAL_NOTIFICACION NUMBER;
V_NUM_NOTIFICACION NUMBER;
V_NUEVO_NUM_NOTIFICACION NUMBER;
V_REPORTE_EMISIONES_ID NUMBER;
V_CURRVAL_REPORTE_EMISIONES NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
    VALUES (1001, '1ABC123', TRUE, SYSDATE, 32);
    INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
    VALUES (1001, 'SERIE001', SYSTIMESTAMP, FALSE, FALSE, TRUE, 'SERIEV001', 1, 1002, 4, 1001);

    INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
    VALUES (1002, '1ABC1232', TRUE, SYSDATE, 32);
    INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
    VALUES (1003, '1ABC1233', TRUE, SYSDATE, 32);
    INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
    VALUES (1004, '1ABC1234', TRUE, SYSDATE, 32);
    INSERT INTO PLACA (PLACA_ID, NUM_PLACA, ES_ACTIVA, FECHA_ASIGNACION, ENTIDAD_ID) 
    VALUES (1005, '1ABC1235', TRUE, SYSDATE, 32);

    INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
    VALUES (1002, 'SERIE0012', SYSTIMESTAMP, FALSE, FALSE, TRUE, 'SERIEV0012', 1, 1002, 4, 1002);
    INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
    VALUES (1003, 'SERIE0013', SYSTIMESTAMP, FALSE, FALSE, TRUE, 'SERIEV0013', 1, 1002, 4, 1003);
    INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
    VALUES (1004, 'SERIE0014', SYSTIMESTAMP, FALSE, FALSE, TRUE, 'SERIEV0014', 1, 1002, 4, 1004);
    INSERT INTO VEHICULO (VEHICULO_ID, NUM_SERIE_DISPOSITIVO, FECHA_ESTATUS, ES_DE_CARGA, ES_TRANSPORTE_PUBLICO, ES_PARTICULAR, NUM_SERIE_VEHICULO, MODELO_ID, PROPIETARIO_ID, ESTATUS_VEHICULO_ID, PLACA_ID)
    VALUES (1005, 'SERIE0015', SYSTIMESTAMP, FALSE, FALSE, TRUE, 'SERIEV0015', 1, 1002, 4, 1005);

    SELECT NOTIFICACION_SEQ.CURRVAL INTO V_CURRVAL_NOTIFICACION 
    FROM DUAL;
    SELECT REPORTE_EMISIONES_SEQ.CURRVAL INTO V_CURRVAL_REPORTE_EMISIONES
    FROM DUAL;

    FOR I IN 1001..1005 LOOP
        SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUM_NOTIFICACION
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN 
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE 
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        WHERE RE.VEHICULO_ID = I;

        SELECT REPORTE_EMISIONES_SEQ.NEXTVAL INTO V_REPORTE_EMISIONES_ID FROM DUAL;
        
        INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, 
            FECHA_REGISTRO, VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
        VALUES(V_REPORTE_EMISIONES_ID, SYSDATE + I, 0.9, 1, I);

        PR_INSERTAR_NOTIFICACION(SYSDATE + I, I,V_NOTIFICACION_ID);

        INSERT INTO REPORTE_EMISIONES_NOTIFICACION(REPORTE_EMISIONES_ID,
            NOTIFICACION_ID)
        VALUES(V_REPORTE_EMISIONES_ID, V_NOTIFICACION_ID);

        SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUEVO_NUM_NOTIFICACION
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN 
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE 
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        WHERE RE.VEHICULO_ID = I; 

        IF V_NUEVO_NUM_NOTIFICACION - V_NUM_NOTIFICACION = 1 THEN
            DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA PARA VEHICULO: '|| I );
        ELSE 
            DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA PARA VEHICULO: '|| I);
        END IF;
    END LOOP;

    
    ROLLBACK;
    EXECUTE IMMEDIATE 'DROP SEQUENCE NOTIFICACION_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE NOTIFICACION_SEQ
                        START WITH ' || v_currval_notificacion || '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE REPORTE_EMISIONES_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE REPORTE_EMISIONES_SEQ
                        START WITH ' || V_CURRVAL_REPORTE_EMISIONES|| '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    
END;
/
SHOW ERRORS;