SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt Insertando licencia por primera vez
Prompt ========================================
DECLARE 
V_NUM_LICENCIAS NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    PR_INSERTAR_LICENCIA(EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), SYSDATE,'1234567', 'B', 1002);
    
    SELECT COUNT(*) INTO V_NUM_LICENCIAS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND TIPO = 'B';
    IF V_NUM_LICENCIAS = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
END;
/
ROLLBACK;
SHOW ERRORS;
Prompt =======================================
Prompt Prueba 2.
prompt Insertando licencias expirada + 1 nueva. 
Prompt ========================================
DECLARE 
V_NUM_LICENCIAS NUMBER;
V_LICENCIA_ANTERIOR_ID_ULTIMA LICENCIA.LICENCIA_ID%TYPE;
V_LICENCIA_ANTERIOR_ID LICENCIA.LICENCIA_ID%TYPE;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    PR_INSERTAR_LICENCIA(EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), SYSDATE-3000,'1234567', 'B', 1002);
    PR_INSERTAR_LICENCIA(EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), SYSDATE,'1234568', 'B', 1002);
    
    SELECT COUNT(*) INTO V_NUM_LICENCIAS
    FROM LICENCIA
    WHERE PROPIETARIO_ID = 1002
    AND TIPO='B';
    
    SELECT LICENCIA_ANTERIOR_ID INTO V_LICENCIA_ANTERIOR_ID_ULTIMA
    FROM LICENCIA
    WHERE FECHA_VENCIMIENTO = (
        SELECT MAX(FECHA_VENCIMIENTO)
        FROM LICENCIA
        WHERE PROPIETARIO_ID = 1002
        AND TIPO = 'B'
    )
    AND PROPIETARIO_ID = 1002
    AND TIPO = 'B';

    SELECT LICENCIA_ID INTO V_LICENCIA_ANTERIOR_ID
    FROM LICENCIA
    WHERE FECHA_VENCIMIENTO = (
         SELECT MAX(FECHA_VENCIMIENTO)
         FROM(
            SELECT LICENCIA_ID, FECHA_VENCIMIENTO
            FROM LICENCIA
            WHERE PROPIETARIO_ID = 1002
            AND TIPO = 'B'
            MINUS
            SELECT LICENCIA_ID, FECHA_VENCIMIENTO
            FROM LICENCIA
            WHERE FECHA_VENCIMIENTO = (
                SELECT MAX(FECHA_VENCIMIENTO)
                FROM LICENCIA
                WHERE PROPIETARIO_ID = 1002
                AND TIPO = 'B'
            )
         )
    )
    AND PROPIETARIO_ID = 1002
    AND TIPO = 'B';
    

    IF V_NUM_LICENCIAS = 2 
        AND V_LICENCIA_ANTERIOR_ID = V_LICENCIA_ANTERIOR_ID_ULTIMA THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
END;
/
ROLLBACK;
SHOW ERRORS;