
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt Insertando notificaciones para un mismo vehiculo
Prompt ========================================


SELECT REPORTE_EMISIONES_SEQ.NEXTVAL FROM DUAL;
SELECT NOTIFICACION_SEQ.NEXTVAL FROM DUAL;

DECLARE
V_NOTIFICACION_ID NUMBER;
V_CURRVAL_NOTIFICACION NUMBER;
V_NUM_NOTIFICACION NUMBER;
V_NUEVO_NUM_NOTIFICACION NUMBER;
V_REPORTE_EMISIONES_ID NUMBER;
V_CURRVAL_REPORTE_EMISIONES NUMBER;
BEGIN
    SELECT NOTIFICACION_SEQ.CURRVAL INTO V_CURRVAL_NOTIFICACION 
    FROM DUAL;
    SELECT REPORTE_EMISIONES_SEQ.CURRVAL INTO V_CURRVAL_REPORTE_EMISIONES
    FROM DUAL;

    SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUM_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN 
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE 
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    WHERE RE.VEHICULO_ID = 5;
    
    FOR I IN 1..10 LOOP
        SELECT REPORTE_EMISIONES_SEQ.NEXTVAL INTO V_REPORTE_EMISIONES_ID FROM DUAL;

        INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, 
            FECHA_REGISTRO, VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
        VALUES(V_REPORTE_EMISIONES_ID, SYSDATE + I, 0.9, 1, 5);

        PR_INSERTAR_NOTIFICACION(SYSDATE + I, 5,V_NOTIFICACION_ID);

        INSERT INTO REPORTE_EMISIONES_NOTIFICACION(REPORTE_EMISIONES_ID,
            NOTIFICACION_ID)
        VALUES(V_REPORTE_EMISIONES_ID, V_NOTIFICACION_ID);
    END LOOP;

    SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUEVO_NUM_NOTIFICACION
    FROM NOTIFICACION NT
    JOIN REPORTE_EMISIONES_NOTIFICACION REN 
        ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
    JOIN REPORTE_EMISIONES RE 
        ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
    WHERE RE.VEHICULO_ID = 5; 
    IF V_NUEVO_NUM_NOTIFICACION - V_NUM_NOTIFICACION = 10 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF;
    ROLLBACK;
    COMMIT;
    EXECUTE IMMEDIATE 'DROP SEQUENCE NOTIFICACION_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE NOTIFICACION_SEQ
                        START WITH ' || v_currval_notificacion || '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE REPORTE_EMISIONES_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE REPORTE_EMISIONES_SEQ
                        START WITH ' || V_CURRVAL_REPORTE_EMISIONES|| '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    
END;
/

SHOW ERRORS;


Prompt =======================================
Prompt Prueba 2.
prompt Insertando notificaciones para diferentes vehiculos
Prompt ========================================


SELECT REPORTE_EMISIONES_SEQ.NEXTVAL FROM DUAL;
SELECT NOTIFICACION_SEQ.NEXTVAL FROM DUAL;

DECLARE
V_NOTIFICACION_ID NUMBER;
V_CURRVAL_NOTIFICACION NUMBER;
V_NUM_NOTIFICACION NUMBER;
V_NUEVO_NUM_NOTIFICACION NUMBER;
V_REPORTE_EMISIONES_ID NUMBER;
V_CURRVAL_REPORTE_EMISIONES NUMBER;
BEGIN
    SELECT NOTIFICACION_SEQ.CURRVAL INTO V_CURRVAL_NOTIFICACION 
    FROM DUAL;
    SELECT REPORTE_EMISIONES_SEQ.CURRVAL INTO V_CURRVAL_REPORTE_EMISIONES
    FROM DUAL;

    FOR I IN 1..5 LOOP
        SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUM_NOTIFICACION
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN 
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE 
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        WHERE RE.VEHICULO_ID = I;

        SELECT REPORTE_EMISIONES_SEQ.NEXTVAL INTO V_REPORTE_EMISIONES_ID FROM DUAL;
        
        INSERT INTO REPORTE_EMISIONES(REPORTE_EMISIONES_ID, 
            FECHA_REGISTRO, VALOR_MEDIDO, GAS_ID, VEHICULO_ID)
        VALUES(V_REPORTE_EMISIONES_ID, SYSDATE + I, 0.9, 1, I);

        PR_INSERTAR_NOTIFICACION(SYSDATE + I, I,V_NOTIFICACION_ID);

        INSERT INTO REPORTE_EMISIONES_NOTIFICACION(REPORTE_EMISIONES_ID,
            NOTIFICACION_ID)
        VALUES(V_REPORTE_EMISIONES_ID, V_NOTIFICACION_ID);

        SELECT NVL(MAX(NUM_NOTIFICACION),0) INTO V_NUEVO_NUM_NOTIFICACION
        FROM NOTIFICACION NT
        JOIN REPORTE_EMISIONES_NOTIFICACION REN 
            ON REN.NOTIFICACION_ID = NT.NOTIFICACION_ID
        JOIN REPORTE_EMISIONES RE 
            ON RE.REPORTE_EMISIONES_ID = REN.REPORTE_EMISIONES_ID
        WHERE RE.VEHICULO_ID = I; 

        IF V_NUEVO_NUM_NOTIFICACION - V_NUM_NOTIFICACION = 1 THEN
            DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA PARA VEHICULO: '|| I );
        ELSE 
            DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA PARA VEHICULO: '|| I);
        END IF;
    END LOOP;

    
    ROLLBACK;
    COMMIT;
    EXECUTE IMMEDIATE 'DROP SEQUENCE NOTIFICACION_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE NOTIFICACION_SEQ
                        START WITH ' || v_currval_notificacion || '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE REPORTE_EMISIONES_SEQ';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE REPORTE_EMISIONES_SEQ
                        START WITH ' || V_CURRVAL_REPORTE_EMISIONES|| '
                        INCREMENT BY 1
                        NOMAXVALUE
                        NOCYCLE';
    
END;
/
SHOW ERRORS;