
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt ACTUALIZACION EXITOSA PENDIENTE DE VERIFICACION A EN REGLA
Prompt ========================================
DECLARE 
V_NUEVO_ESTATUS_ID ESTATUS_VEHICULO.ESTATUS_VEHICULO_ID%TYPE;
BEGIN 
    UPDATE VEHICULO SET 
        ESTATUS_VEHICULO_ID = 4,
        FECHA_ESTATUS = SYSTIMESTAMP
    WHERE VEHICULO_ID = 1;
    INSERT INTO VERIFICACION(VERIFICACION_ID, FECHA_VERIFICACION, 
        FOLIO, CLAVE_VERIFICENTRO, VEHICULO_ID)
    VALUES(1001, SYSTIMESTAMP + 1, 'VERIF1001', '00001', 1);
    INSERT INTO REPORTE_VERIFICENTRO(GAS_ID, VERIFICACION_ID, VALOR_MEDIDO)
    VALUES(1, 1001, 0.1),
        (2, 1001, 0.1),
        (3, 1001, 0.1),
        (4, 1001, 0.1);
    PR_ACTUALIZAR_ESTATUS_VERIF_APROBADA(1001);
    SELECT ESTATUS_VEHICULO_ID INTO V_NUEVO_ESTATUS_ID
    FROM VEHICULO
    WHERE VEHICULO_ID = 1;
    IF V_NUEVO_ESTATUS_ID = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 2
prompt ACTUALIZACION FALLIDA PORQUE LA VERIFICACION NO COINCIDE CON LA DEL ESTATUS
Prompt ========================================
DECLARE 
V_NUEVO_ESTATUS_ID ESTATUS_VEHICULO.ESTATUS_VEHICULO_ID%TYPE;
V_EXCEPTION VARCHAR2(20);
BEGIN 
    UPDATE VEHICULO SET 
        ESTATUS_VEHICULO_ID = 4,
        FECHA_ESTATUS = SYSTIMESTAMP
    WHERE VEHICULO_ID = 1;
    INSERT INTO VERIFICACION(VERIFICACION_ID, FECHA_VERIFICACION, 
        FOLIO, CLAVE_VERIFICENTRO, VEHICULO_ID)
    VALUES(1001, SYSTIMESTAMP - 1, 'VERIF1001', '00001', 1);
    INSERT INTO REPORTE_VERIFICENTRO(GAS_ID, VERIFICACION_ID, VALOR_MEDIDO)
    VALUES(1, 1001, 0.1),
        (2, 1001, 0.1),
        (3, 1001, 0.1),
        (4, 1001, 0.1);
    PR_ACTUALIZAR_ESTATUS_VERIF_APROBADA(1001);
    SELECT ESTATUS_VEHICULO_ID INTO V_NUEVO_ESTATUS_ID
    FROM VEHICULO
    WHERE VEHICULO_ID = 1;
    EXCEPTION  
        WHEN OTHERS THEN
            V_EXCEPTION := ''||SQLCODE;
            IF V_EXCEPTION = '-20006' THEN
                DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
            ELSE 
                DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
            END IF;  
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;


Prompt =======================================
Prompt Prueba 3
prompt ACTUALIZACION FALLIDA PORQUE NO TENÍA VERIFICACION PENDIENTE
Prompt ========================================
DECLARE 
V_NUEVO_ESTATUS_ID ESTATUS_VEHICULO.ESTATUS_VEHICULO_ID%TYPE;
V_EXCEPTION VARCHAR2(20);
BEGIN 
    UPDATE VEHICULO SET 
        ESTATUS_VEHICULO_ID = 3,
        FECHA_ESTATUS = SYSTIMESTAMP
    WHERE VEHICULO_ID = 1;
    INSERT INTO VERIFICACION(VERIFICACION_ID, FECHA_VERIFICACION, 
        FOLIO, CLAVE_VERIFICENTRO, VEHICULO_ID)
    VALUES(1001, SYSTIMESTAMP + 1, 'VERIF1001', '00001', 1);
    INSERT INTO REPORTE_VERIFICENTRO(GAS_ID, VERIFICACION_ID, VALOR_MEDIDO)
    VALUES(1, 1001, 0.1),
        (2, 1001, 0.1),
        (3, 1001, 0.1),
        (4, 1001, 0.1);
    PR_ACTUALIZAR_ESTATUS_VERIF_APROBADA(1001);
    SELECT ESTATUS_VEHICULO_ID INTO V_NUEVO_ESTATUS_ID
    FROM VEHICULO
    WHERE VEHICULO_ID = 1;
    EXCEPTION  
        WHEN OTHERS THEN
            V_EXCEPTION := ''||SQLCODE;
            IF V_EXCEPTION = '-20005' THEN
                DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
            ELSE 
                DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
            END IF;          
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 4.
prompt ACTUALIZACION NO EXITOSA POR VALOR NO PERMITIDO DE UN GAS
Prompt ========================================
DECLARE 
V_NUEVO_ESTATUS_ID ESTATUS_VEHICULO.ESTATUS_VEHICULO_ID%TYPE;
BEGIN 
    UPDATE VEHICULO SET 
        ESTATUS_VEHICULO_ID = 4,
        FECHA_ESTATUS = SYSTIMESTAMP
    WHERE VEHICULO_ID = 1;
    INSERT INTO VERIFICACION(VERIFICACION_ID, FECHA_VERIFICACION, 
        FOLIO, CLAVE_VERIFICENTRO, VEHICULO_ID)
    VALUES(1001, SYSTIMESTAMP + 1, 'VERIF1001', '00001', 1);
    INSERT INTO REPORTE_VERIFICENTRO(GAS_ID, VERIFICACION_ID, VALOR_MEDIDO)
    VALUES(1, 1001, 0.1),
        (2, 1001, 0.1),
        (3, 1001, 0.1),
        (4, 1001, 0.9);
    PR_ACTUALIZAR_ESTATUS_VERIF_APROBADA(1001);
    SELECT ESTATUS_VEHICULO_ID INTO V_NUEVO_ESTATUS_ID
    FROM VEHICULO
    WHERE VEHICULO_ID = 1;
    IF V_NUEVO_ESTATUS_ID = 4 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;
