CONNECT SBM_PROY_ADMIN/123456789@SBMBD_S1SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt INSERTAR VARIAS FALTAS
Prompt ========================================

DECLARE
V_FOLIO_ACTUAL NUMBER;
V_FOLIO_NUEVO NUMBER;
BEGIN
    SELECT NVL(MAX(FOLIO),0) INTO V_FOLIO_ACTUAL
    FROM FALTA F
    WHERE F.PROPIETARIO_ID = 1;
    FOR I IN 1..10 LOOP
        PR_INSERTAR_FALTA(1,SYSTIMESTAMP,'FALTA '||I, I, EMPTY_CLOB());
    END LOOP;
    SELECT NVL(MAX(FOLIO),0) INTO V_FOLIO_NUEVO
    FROM FALTA F
    WHERE F.PROPIETARIO_ID = 1;
    IF V_FOLIO_NUEVO - V_FOLIO_ACTUAL = 10 THEN
        DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA');
    END IF; 
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;

Prompt =======================================
Prompt Prueba 2.
prompt INSERTAR UNA FALTA POR CADA PROPIETARIO
Prompt ========================================

INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL)
VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL)
VALUES (1003, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF2', 'PACO2@EXAMPLE.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL)
VALUES (1004, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF3', 'PACO3@EXAMPLE.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL)
VALUES (1005, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF4', 'PACO4@EXAMPLE.COM');
INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL)
VALUES (1006, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF5', 'PACO5@EXAMPLE.COM');

DECLARE
V_FOLIO_ACTUAL NUMBER;
V_FOLIO_NUEVO NUMBER;
BEGIN
    
    FOR I IN 1002..1006 LOOP
        SELECT NVL(MAX(FOLIO),0) INTO V_FOLIO_ACTUAL
        FROM FALTA F
        WHERE F.PROPIETARIO_ID = I;
        PR_INSERTAR_FALTA(I,SYSTIMESTAMP,'FALTA '||(I-1000), I-1000, EMPTY_CLOB());
        SELECT NVL(MAX(FOLIO),0) INTO V_FOLIO_NUEVO
        FROM FALTA F
        WHERE F.PROPIETARIO_ID = I;
        IF V_FOLIO_NUEVO - V_FOLIO_ACTUAL = 1 THEN
            DBMS_OUTPUT.PUT_LINE('PRUEBA EXITOSA PARA PROPIETARIO: ' ||I);
        ELSE 
            DBMS_OUTPUT.PUT_LINE('PRUEBA NO EXITOSA PARA PROPIETARIO: ' ||I);
        END IF; 
    END LOOP;
    
END;
/
ROLLBACK;
COMMIT;
SHOW ERRORS;
