
CREATE OR REPLACE PROCEDURE PR_OBTENER_IMAGEN(
    P_LICENCIA_ID IN NUMBER,
    P_RUTA_DESTINO IN VARCHAR2,
    P_ATRIBUTO IN VARCHAR2
) IS
    V_BLOB BLOB;
    V_OUTPUT_FILE UTL_FILE.FILE_TYPE;
    V_BUFFER RAW(32767);
    V_CHUNK_SIZE NUMBER := 32767; 
    V_POS NUMBER := 1;
    V_BLOB_LEN NUMBER;
BEGIN
    EXECUTE IMMEDIATE 
        'SELECT ' || P_ATRIBUTO || ' FROM LICENCIA WHERE LICENCIA_ID = :id'
        INTO V_BLOB
        USING P_LICENCIA_ID;

    V_BLOB_LEN := DBMS_LOB.GETLENGTH(V_BLOB);

    V_OUTPUT_FILE := UTL_FILE.FOPEN('BLOBS_DIR', P_RUTA_DESTINO, 'wb', 32767);

    WHILE V_POS < V_BLOB_LEN LOOP
        DBMS_LOB.READ(V_BLOB, V_CHUNK_SIZE, V_POS, V_BUFFER);
        UTL_FILE.PUT_RAW(V_OUTPUT_FILE, V_BUFFER, TRUE);
        V_POS := V_POS + V_CHUNK_SIZE;
    END LOOP;

    UTL_FILE.FCLOSE(V_OUTPUT_FILE);
END;
/
SHOW ERRORS;