
CREATE OR REPLACE PROCEDURE PR_OBTENER_BLOB(
    P_NOMBRE_ARCHIVO IN VARCHAR2,
    P_BLOB IN OUT BLOB
) IS
    V_BFILE BFILE; 
    V_DEST_OFFSET NUMBER :=1;
    V_SRC_OFFSET NUMBER :=1;
BEGIN
    V_BFILE := BFILENAME('BLOBS_DIR',''||P_NOMBRE_ARCHIVO);

    DBMS_LOB.FILEOPEN(V_BFILE, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.CREATETEMPORARY(P_BLOB, true);
    DBMS_LOB.LOADBLOBFROMFILE(P_BLOB,V_BFILE, DBMS_LOB.LOBMAXSIZE,V_DEST_OFFSET,V_SRC_OFFSET);
    
    DBMS_LOB.FILECLOSE(V_BFILE);
END;
/
SHOW ERRORS;
