
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt Insertando licencia con foto
Prompt ========================================
DECLARE 
    V_NUM_LICENCIAS NUMBER;
    V_BLOB BLOB;
    V_LONGITUD_BLOB NUMBER;
    V_LICENCIA_ID NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);

    PR_OBTENER_BLOB('foto1.jpg',V_BLOB);
    PR_INSERTAR_LICENCIA(V_BLOB, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), SYSDATE,'1234567', 'B', 1002);

    SELECT LICENCIA_SEQ.CURRVAL INTO V_LICENCIA_ID;

    SELECT DBMS_LOB.GETLENGTH(FOTO) INTO V_LONGITUD_BLOB
    FROM LICENCIA
    WHERE LICENCIA_ID = V_LICENCIA_ID;

    DBMS_OUTPUT.PUT_LINE('TAMAÑO DE BLOB: '||V_LONGITUD_BLOB);
END;
/
ROLLBACK;
SHOW ERRORS;