
SET SERVEROUTPUT ON
SET AUTOCOMMIT OFF
Prompt =======================================
Prompt Prueba 1.
prompt Obteniendo imagen en BLOBS_DIR
Prompt ========================================
DECLARE 
    V_NUM_LICENCIAS NUMBER;
    V_BLOB BLOB;
    V_LONGITUD_BLOB NUMBER;
    V_LICENCIA_ID NUMBER;
BEGIN
    INSERT INTO PROPIETARIO(PROPIETARIO_ID, NOMBRE, AP_PATERNO, AP_MATERNO, RFC, EMAIL, DERECHO_LICENCIA)
    VALUES (1002, 'FRANCISCO', 'CHAVEZ', 'PEREZ', 'RFCRFRFRF1', 'PACO1@EXAMPLE.COM', TRUE);
    PR_OBTENER_BLOB('foto1.jpg',V_BLOB);
    PR_INSERTAR_LICENCIA(V_BLOB, EMPTY_BLOB(), EMPTY_BLOB(), EMPTY_BLOB(), SYSDATE,'1234567', 'B', 1002);
    
    SELECT LICENCIA_SEQ.CURRVAL INTO V_LICENCIA_ID;

    PR_OBTENER_IMAGEN(V_LICENCIA_ID,'foto1_copia.jpg','FOTO');
END;
/
ROLLBACK;
SHOW ERRORS;